const Estado = Object.freeze({
	INICIAL: 1,
	SAGUAO: 2,
	SALA: 3,
	PREPARACAO: 4,
	PRONTO: 5,
	JOGO: 6,
	RESULTADO: 7,
	ATACANDO: 8,
	DEFENDENDO: 9,
	DESCONECTADO: 10,
	DESISTENTE: 11,
	DERROTADO: 12,
	VENCEDOR: 13
});

module.exports = Estado;